apiVersion: v1
kind: Service
metadata:
  name: k8sworkshop-service
spec:
  ports:
    - port: 80
      name: web
      targetPort: 80
  selector:
    component: k8sworkshop-deployment
  type: NodePort
