apiVersion: v1
kind: Pod
metadata:
  name: k8sworkshop-pod
spec:
  containers:
  - env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    image: targetprocess/k8sworkshop:initial
    imagePullPolicy: Always
    name: k8sworkshop-pod
    ports:
    - containerPort: 80
      protocol: TCP
